### ISSUE TITLE
Stop it getting progressively longer?

### ISSUE THREAD

**Issue by joejlo** [commodo/glitch-animation-effect#1]
Is there way you can add a limit to the time in between glitches, or randomize it?

**Comment by commodo** [comment]
if you want to control time in-between glitches, you just edit this line https://github.com/commodo/glitch-animation-effect/blob/master/glitch-execute.js#L53

i think changing
```
setTimeout(render_glitches, times_rendered * getRandomInt(500, 1500));
```

to 
```
setTimeout(render_glitches, getRandomInt(MIN, MAX));
```
would be sufficient

the initial idea was to make glitches render for `TOTAL_TIMES_TO_RENDER` times, and then stop;
this was for when you open-up a site the first time;
and to make the times in-between glitches longer, so that you can use the site if you need to

**Comment by commodo** [comment]
maybe i'll just add a change for that too

**Comment by commodo** [comment]
so, if you pull the latest change https://github.com/commodo/glitch-animation-effect/commit/8e6c3486aab02b2145142e4b7bdb54d3e273194f

if you set `GLITCH_INTERVAL_PROGRESSIVE=0`
and play with the `GLITCH_INTERVAL_MIN/MAX`, it should be what you want

**Comment by joejlo** [comment]
I tried the first suggestion and it didn't work, I think maybe because setting it to `MAX` makes the extremities too large and you could waiting and infinite amount of time for the glitch?

I changed it to `setTimeout(render_glitches, getRandomInt(100, 10000));` and it seems to get the effect I want. 

Let me try your last suggestion...

**Comment by joejlo** [comment]
Yeah that works perfectly if I change the MIN/MAX intervals!

This is the best glitch effect I've come across and really works for my current project, thanks a bunch!

**Comment by commodo** [comment]
you may need to do a Ctrl + Shift + R (that's in Firefox ; maybe Chrome too) ;
maybe this JS code get's cached by the browser

I've tested my change here: http://rank24.net/%7Esandu/glitch_test/
(to put my money where my mouth is ; so to speak)

Also, notice, that 10 seconds is a long time when testing.

**Comment by commodo** [comment]
Cool. Thanks 

This glitch is something I did for a project and thought about sharing it.
I've only re-used some other guy's glitch-effect-frame manipulation into an animation ; not sure why he didn't do it ; it makes a lot of sense to do it.

Looking at the code now, I've got a sudden urge to make it nicer (refactor) ; but I think it would take some time to test.

One thing I could try to do now, real quick [and I've wanted to do initially] is to regenerate the frames every once in a while.

**Comment by joejlo** [comment]
The 10 seconds works great I'll upload and show you what I'm using it for shortly.

Is it set to stop after a while? I've noticed that if the page is open for about a minute or so, the effect stops

**Comment by commodo** [comment]
after 30 gltiches, yes
it stops
`TOTAL_TIMES_TO_RENDER  = 30`

maybe for the demo, it makes sense to make it loop indefinitely

**Comment by joejlo** [comment]
Ah so how would one set it to indefinite?

Here's the current project with glitch, not fully functioning yet but you get the idea - http://vulgar.thevulgarcollective.co.uk/peur/html/login.html#

**Comment by commodo** [comment]
I've update the code a bit.
I've changed the indentation too (because it scratched my eyes a bit).

Added this change: https://github.com/commodo/glitch-animation-effect/commit/3e04cc86fb8858706f854b30cec6047abcf3faff
if you set `GLITCH_RENDER_COUNT`  to 0 (I think it's default now), it will glitch indefinitely
which makes sense to keep it like this for the demo page

**Comment by joejlo** [comment]
That works great dude!

**Comment by commodo** [comment]
cool :)
glad it worked

then can we close this ? or is there something else that you'd need ?

**Comment by joejlo** [comment]
All done, thanks a lot!
