### ISSUE TITLE
Initialisation and callbacks

### ISSUE THREAD

**Issue by smth** [commodo/glitch-animation-effect#2]
I think it'd be nice to be able to trigger some other action, once the animations are complete (assuming you limit the count). Would also be good to have some control over when are where the scripts takes effect. I'm thinking this could then be used as an intro, or transition.

So for example you might want to specify that the script run on an element with a specific class, then after x amount of animations that element is hidden and something else revealed.

**Comment by commodo** [comment]
hey
sorry for taking long to reply
was busy and traveling a bit the last couple of days

i'll look into it;

**Comment by commodo** [comment]
@smth 
please check this demo page:
http://rank24.net/%7Esandu/glitch_test/index3.html

i admit the `done_callback` being a simple `alert()` is a bit obtuse, but of the the sake of a demo, it should do;

i updated the readme with a few more demo pages ; 

now you should also be able to glitch individual elements

initializing a glitch object should be doable without needing to fiddle in the `glitch-execute.js` 
so something like

```
            window.onload = function() {
                var gl = Object.create(glitch_exec);
                 <add preferred params here>
                gl.done_callback = function() { }
                gl.start(<div>);
            }
```

i'm hoping this is in the ball-park of what you requested

fwiw: this lib is something i wrote about 4 years ago real quick and decided to put it up online for reference ; some of the constructs you'll see are not very JS-ish, since I mostly speak C nowadays

if you have suggestions, please send them and i'll take a look
or feel free to send code/PRs

thanks
Alex

**Comment by commodo** [comment]
btw ; the `window.onload` hook i used is for demo ; you can hook that function to whatever you need to start glitching an element

**Comment by commodo** [comment]
closing this;
if it's still valid please re-open
